- hosts: ubuntu
  gather_facts: False
  
  tasks:
  - name: install python 2
    become: yes
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-apt)
  - name: install python-apt
    become: yes
    command: apt install python-apt -y
